export const STUDENTS_LIST_REQUEST = 'STUDENTS_LIST_REQUEST'
export const STUDENTS_LIST_SUCCESS = 'STUDENTS_LIST_SUCCESS'
export const STUDENTS_LIST_FAIL= 'STUDENTS_LIST_FAIL'

export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST'
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS'
export const STUDENT_DETAILS_FAIL= 'STUDENT_DETAILS_FAIL'

export const STUDENT_DELETE_REQUEST = 'STUDENT_DELETE_REQUEST'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const STUDENT_DELETE_FAIL= 'STUDENT_DELETE_FAIL'

export const STUDENT_CREATE_REQUEST = 'STUDENT_CREATE_REQUEST'
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS'
export const STUDENT_CREATE_FAIL= 'STUDENT_CREATE_FAIL'
export const STUDENT_CREATE_RESET= 'STUDENT_CREATE_RESET'


export const STUDENT_UPDATE_REQUEST='STUDENT_UPDATE_REQUEST'
export const STUDENT_UPDATE_SUCCESS='STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL='STUDENT_UPDATE_FAIL'
export const STUDENT_UPDATE_RESET='STUDENT_UPDATE_RESET'


export const USER_LIST_REQUEST='USER_LIST_REQUEST'
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS'
export const USER_LIST_FAIL='USER_LIST_FAIL'
export const USER_LIST_RESET='USER_LIST_RESET'